version: "3.9"

services:
  nextjs:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: smartsociety-nextjs
   ports:
    - "3000:3000"
   env_file:
    - .env
  socket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    container_name: smartsociety-socket
    ports:
      - "3001:3001"
    env_file:
      - .env