apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: smartsociety
  labels:
    app: nextjs-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-server
  template:
    metadata:
      labels:
        app: nextjs-server
    spec:
      containers:
      - name: nextjs
        image: samradhi/smartsociety-nextjs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
             name: nextjs-config
        - secretRef:
             name: nextjs-secret