apiVersion: v1
kind: Service
metadata:
  name: socket-service
  namespace: smartsociety
spec:
  selector:
    app: socket-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3001
  type: LoadBalancer