apiVersion: v1
kind: Secret
metadata:
  name: nextjs-secret
  namespace: smartsociety
type: Opaque

stringData:
  MONGO_URL: "<MONGO_URL>"
  NEXTAUTH_SECRET: "<NEXTAUTH_SECRET>"
  CLOUD_NAME: "<CLOUD_NAME>"
  API_KEY: "<API_KEY>"
  API_SECRET: "<API_SECRET>"
  CLOUD_API_SECRET: "<CLOUD_API_SECRET>"
  CLOUD_API_KEY: "<CLOUD_API_KEY>"
  EMAIL_USER: "<EMAIL_USER>"
  EMAIL_PASS: "<EMAIL_PASS>"
  CRON_SECRET: "<CRON_SECRET>"
  SECRET_KEY_STRIPE: "<SECRET_KEY_STRIPE>"
  STRIPE_SECRET_KEY: "<STRIPE_SECRET_KEY>"
  NEXT_PUBLIC_URL: "<NEXT_PUBLIC_URL>"
  NEXTAUTH_URL: "<NEXTAUTH_URL>"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "<NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY>"
  NEXT_PUBLIC_SOCKET_SERVER: "<NEXT_PUBLIC_SOCKET_SERVER>"