apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: smartsociety
spec:
  selector:
    app: nextjs-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP