apiVersion: v1
kind: Service
metadata:
  name: socket-service
  namespace: smartsociety
spec:
  selector:
    app: socket-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}
  type: {{ .Values.service.type}}